//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid ResourceAI = new Guid("36716ae6-dceb-4e16-b993-cc272c9c6efe");
		public static readonly Guid ResourceManager = new Guid("1317e8c2-b881-4496-8619-c9e197a86f0e");
		public static readonly Guid Tutorial1 = new Guid("92cbf7ce-7e45-4fb0-9bca-b10db358b779");

    }
}
